version: '3.7'
services:
  database:
    container_name: database
    build: ./database
    ports:
      - 27017:27017
    restart: always
    networks:
      - backend
  database-seed:
    container_name: database-seed
    build: ./database/seed
    depends_on:
      - database
    networks:
      - backend

  strapi:
    container_name: strapi
    build: ./strapi
    ports:
      - 1337:1337
    depends_on:
      - database-seed
    networks:
      - backend
  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - strapi
    environment:
      - MONGO_URI=mongodb://localhost:27017
    networks:
      - backend
volumes:
  mongodata:
  resources:
networks:
  backend:
    name: backend
    driver: bridge
